{% set version = "0.7.3" %}

package:
  name: libgpuarray
  version: {{ version }}

source:
  fn: libgpuarray-{{ version }}.tar.gz
  url: https://github.com/Theano/libgpuarray/releases/download/v{{ version }}/libgpuarray-{{ version }}.tar.gz
  sha256: f2b6732e6ed44ecf30d31cd3ad50a1604abc7fd5cc2c004cbf11497b654a2a0c

build:
  number: 0
  skip: true  # [win and py35]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py35]
    - vc14    # [win and py36]

requirements:
  build:
    - toolchain
    - python     # [win]
    - cmake

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}                      # [win]
  commands:
    - test -f ${PREFIX}/lib/libgpuarray.dylib                   # [osx]
    - test -f ${PREFIX}/lib/libgpuarray.so                      # [linux]
    - if not exist %PREFIX%\\Library\\lib\\gpuarray.lib exit 1  # [win]

about:
  home: http://github.com/Theano/libgpuarray
  license: ISC
  license_file: LICENSE
  summary: 'Library to manipulate arrays on GPU'
  doc_url: http://deeplearning.net/software/libgpuarray/
  dev_url: http://github.com/Theano/libgpuarray

extra:
  recipe-maintainers:
    - abergeron
