{% set version = "0.6.4" %}

package:
  name: libgpuarray
  version: {{ version }}

source:
  fn: libgpuarray-{{ version }}.tar.gz
  url: https://github.com/Theano/libgpuarray/archive/v{{ version }}.tar.gz
  sha256: beb4300ae6b0efdfd2993b8d6bbd783ea56030c27a79bc75a318111a7c14cd8f

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - toolchain
    - cmake
    - python
    - cython >=0.25
    - numpy x.x
    - mako
    - setuptools

  run:
    - python
    - numpy x.x
    - mako
    - six

test:
  commands:
    - test -f ${PREFIX}/lib/libgpuarray.dylib  # [osx]
    - test -f ${PREFIX}/lib/libgpuarray.so  # [linux]
    - if not exist %PREFIX%\\Library\\lib\\gpuarray.lib exit 1  # [win]
  imports:
    - pygpu
    - pygpu.gpuarray

about:
  home: http://github.com/Theano/libgpuarray
  license: ISC
  license_file: LICENSE
  summary: 'Library to manipulate arrays on GPU'
  doc_url: http://deeplearning.net/software/libgpuarray/
  dev_url: http://github.com/Theano/libgpuarray

extra:
  recipe-maintainers:
    - abergeron
