travis:
  secure:
    BINSTAR_TOKEN: X9JfaBvKsRGknPt6hHTE+HXntBDV00Di9BYT1BXcvBGAaYIigY/NGoiGf6DskfFxfCq8WNQbx2qySarYcp8qNPshseHZPjn0StwLV+LpV/UnAilfnvmNC01YUwbaNKDQ52dTYywuV8x+nSC+DscRsi295mzW4MEAFPiLX+zFAO6SR/D8mSDXIMG4uPVylvqKJqeH5hGAKPQuHegLfbN1Of6nmQ5qF8l2WGXbVUE/1y+sHTRgw0D0cciqi+fNizJkFsm8I8pnscZV9MmF4ziHgHT0FEU+E9ZupOOtOnhaZr2nUQHwWiXL+Fn3Z0C44Hh9wUcdvEQZpU5b2AKYCoWHOZxfMKUBo1kHnH+ZSV19xrEmrVUb/9mbXjkyjYCs0+yiJe/ZsZEuhusikRgoCy2WWFC8mIZxAJacu7su5P2bl4cpoOHL5p57euWT6gScxgNVs9P4s2OYtwHxp8tmuA135k+QuJHwUQkyChMZUb+J+fUsDN1xFuTBbeHdn2U+LRbncjv3DnPPleqCwFIBjo62+TfoPSL6DK5Db472fNHTYS/S60th15h2DqloGEsJcb6n5pGdrCHIACCd7DO+xddnDRNt7VYg+eOqgy5Cb9qch+E9ZiKM9kQMVcEZpUG62ADCqCc6/5KH0r1yCSsIcaslFitxwCXsXmRRzbnLCqEkxE8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
