travis:
  secure:
    BINSTAR_TOKEN: dkxjHG8VLKIg/XPGYiK2zkcAYh3x1Jq7FjJvQ7JDlWKwhkYUL0+K9F5+pdIFTRZWw7dCcecW0a2VNSFq+q5gvyD/xzD0rfuvezL/4R4YXjNXsvBGFCYFa7LrfJUeOKGvovFUsaER0Udj7F6P2/ePjVxf/rsAwUQgQynoN3mW84yrLBdZUZg1imxH2CSff0veNKwpI339yYqEvQNab7rVnGtXUBzKcp0xAVNs9lZ81J+t3wvtX8vZiynXfGIH0B3/ABwKNPIgm7hfEAa4fD0R6NNneFwDKVgPaQoH9M11RhbcwDlwTubZVRX6SkSmQuRYYh+X2M6xIQYUeswJHg4NSvLJGHZVwafI5Mz/JLp5xdZML7jhp71yVFERLdQ1so9+DwHP1UcVmC8vVp/HzkvmliUuv0gMb24mMZ0B71/rdwt6zwft3AxWS9zZjiMaK3/RHDeQdBk6T5LZ0OlL1GHDIfI0aI/ztVNUdW1B/SX8coRpnPe4t/HVLRSHmlbVTzaDcY4q7e2sSNXkLEAzNXb93eokHalODXaMsP93i5YvtwGmwb9mV3f4h4IoUiqKb0FRKe+u+OErC/EPxyNHTB3+4kFMh/hN6VtsFmZAmG4QwrscTtrkY3oev8kSHGrVazeW39FL232f8uQ1LORTPRcGo1PtsZYj9TKB7dhF1lVhc8U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
